---
- name: "Add the new gpg key"
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id="58118E89F3A912897C070ADBF76221572C52609D" state=present
  register: keyadded

- name: "Add /etc/apt/sources.list.d/docker.list"
  when: keyadded|success
  copy: src=docker.list dest=/etc/apt/sources.list.d owner=root group=root
  register: listadded

- name: "Update the package lists"
  when: listadded|success
  apt: update_cache=true
  register: updated

- name: "Install required packages"
  when: updated|success
  apt: name={{item}} state=installed
  with_items:
    - docker-engine
    - python-pip
  register: installed

- name: Start Docker
  when: installed|success
  service: name=docker state=started

- name: "Install docker-py"
  when: installed|success
  pip: name=docker-py state=present