---
- name: Add GitLab's runner official repository via apt-get 
  shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | sudo bash

- name: Install gitlab-ci-multi-runner
  apt: pkg=gitlab-ci-multi-runner state=installed